-- Seed team_profiles for all 44 WC2026 teams
-- Run: Supabase dashboard → SQL editor → paste and execute
-- ON CONFLICT updates all fields so safe to re-run

INSERT INTO team_profiles (team_code, team_name, fifa_ranking, confederation, coach_name, formation, playing_style) VALUES
('ALG', 'Algeria',           36, 'CAF',      'Vladimir Petkovic',    '4-3-3',   'Technical, attacking'),
('ARG', 'Argentina',          1, 'CONMEBOL', 'Lionel Scaloni',       '4-3-3',   'Technical, pressing'),
('AUS', 'Australia',         23, 'AFC',      'Tony Popovic',         '4-3-3',   'High energy, direct'),
('AUT', 'Austria',           25, 'UEFA',     'Ralf Rangnick',        '4-2-2-2', 'High press, aggressive'),
('BEL', 'Belgium',            4, 'UEFA',     'Domenico Tedesco',     '4-2-3-1', 'Attacking, creative'),
('BIH', 'Bosnia-Herzegovina',63, 'UEFA',     'Sergej Barbarez',      '4-2-3-1', 'Physical, direct'),
('BRA', 'Brazil',             3, 'CONMEBOL', 'Carlo Ancelotti',      '4-2-3-1', 'Attacking, creative'),
('CAN', 'Canada',            48, 'CONCACAF', 'Jesse Marsch',         '4-3-3',   'High energy, direct'),
('CPV', 'Cape Verde',        66, 'CAF',      'Pedro Brito',          '4-4-2',   'Organized, physical'),
('COL', 'Colombia',          20, 'CONMEBOL', 'Nestor Lorenzo',       '4-3-3',   'Technical, aggressive'),
('CRO', 'Croatia',            9, 'UEFA',     'Zlatko Dalic',         '4-3-3',   'Technical, experienced'),
('CUW', 'Curacao',           78, 'CONCACAF', 'Remko Bicentini',      '4-3-3',   'Defensive, organized'),
('CZE', 'Czechia',           37, 'UEFA',     'Ivan Hasek',           '4-2-3-1', 'Organized, counter'),
('COD', 'DR Congo',          57, 'CAF',      'Sebastien Desabre',    '4-3-3',   'Athletic, direct'),
('EGY', 'Egypt',             34, 'CAF',      'Hossam Hassan',        '4-2-3-1', 'Technical, defensive'),
('ENG', 'England',            5, 'UEFA',     'Thomas Tuchel',        '4-3-3',   'Possession, technical'),
('FRA', 'France',             2, 'UEFA',     'Didier Deschamps',     '4-3-3',   'Balanced, powerful'),
('GER', 'Germany',           12, 'UEFA',     'Julian Nagelsmann',    '4-2-3-1', 'Attacking, dynamic'),
('GHA', 'Ghana',             55, 'CAF',      'Otto Addo',            '4-2-3-1', 'Athletic, technical'),
('HAI', 'Haiti',             83, 'CONCACAF', 'Marc Collat',          '4-4-2',   'Defensive, organized'),
('IRN', 'Iran',              21, 'AFC',      'Amir Ghalenoei',       '4-5-1',   'Defensive, counter'),
('JPN', 'Japan',             17, 'AFC',      'Hajime Moriyasu',      '4-2-3-1', 'Technical, disciplined'),
('JOR', 'Jordan',            69, 'AFC',      'Hussein Ammouta',      '4-4-2',   'Defensive, organized'),
('MEX', 'Mexico',            16, 'CONCACAF', 'Javier Aguirre',       '4-3-3',   'Counter-attack, physical'),
('MAR', 'Morocco',           14, 'CAF',      'Walid Regragui',       '4-1-4-1', 'Defensive, counter'),
('NED', 'Netherlands',        7, 'UEFA',     'Ronald Koeman',        '4-3-3',   'Attacking, total football'),
('NZL', 'New Zealand',       97, 'OFC',      'Darren Bazeley',       '4-4-2',   'Defensive, direct'),
('NOR', 'Norway',            23, 'UEFA',     'Stale Solbakken',      '4-3-3',   'Direct, physical'),
('PAN', 'Panama',            50, 'CONCACAF', 'Thomas Christiansen',  '4-4-2',   'Defensive, organized'),
('PAR', 'Paraguay',          55, 'CONMEBOL', 'Daniel Garnero',       '4-4-2',   'Defensive, counter'),
('PER', 'Peru',              72, 'CONMEBOL', 'Jorge Fossati',        '4-4-2',   'Organized, counter'),
('POR', 'Portugal',           6, 'UEFA',     'Roberto Martinez',     '4-3-3',   'Attacking, technical'),
('QAT', 'Qatar',             37, 'AFC',      'Marquez Lopez',        '4-3-3',   'Technical, possession'),
('KSA', 'Saudi Arabia',      56, 'AFC',      'Roberto Mancini',      '4-3-3',   'Organized, counter'),
('SCO', 'Scotland',          38, 'UEFA',     'Steve Clarke',         '3-4-2-1', 'Organized, direct'),
('SEN', 'Senegal',           19, 'CAF',      'Aliou Cisse',          '4-3-3',   'Physical, counter'),
('SRB', 'Serbia',            26, 'UEFA',     'Dragan Stojkovic',     '3-4-2-1', 'Physical, attacking'),
('RSA', 'South Africa',      58, 'CAF',      'Hugo Broos',           '4-4-2',   'Defensive, direct'),
('KOR', 'South Korea',       22, 'AFC',      'Hong Myung-bo',        '4-2-3-1', 'High press, technical'),
('ESP', 'Spain',              8, 'UEFA',     'Luis de la Fuente',    '4-3-3',   'Possession, high press'),
('SUI', 'Switzerland',       15, 'UEFA',     'Murat Yakin',          '3-4-2-1', 'Organized, counter'),
('TUR', 'Turkiye',           28, 'UEFA',     'Vincenzo Montella',    '4-2-3-1', 'Technical, organized'),
('URU', 'Uruguay',           18, 'CONMEBOL', 'Marcelo Bielsa',       '4-3-3',   'Intense, collective'),
('USA', 'United States',     13, 'CONCACAF', 'Mauricio Pochettino',  '4-3-3',   'High press, athletic')
ON CONFLICT (team_code) DO UPDATE SET
  team_name      = EXCLUDED.team_name,
  fifa_ranking   = EXCLUDED.fifa_ranking,
  confederation  = EXCLUDED.confederation,
  coach_name     = EXCLUDED.coach_name,
  formation      = EXCLUDED.formation,
  playing_style  = EXCLUDED.playing_style,
  updated_at     = now();
